name: On Points
favicon: null
layout_spectrum: 0.40938650141470134
typography_spectrum: 0.3222633816767484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.28673077281564474
  lightness: 0.7928003468550742
  saturation: 0.004057339625433087
  rhythmicContrast: 0.12384866387583315
purpose: []
